import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/header";
import "./globals.css";
import "./fonts.css";
import "./dashboard.css";
import NavigationMenu from "./components/navmenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="sw-page">
          <Header />
          <NavigationMenu />
        </div>
        {children}
      </body>
    </html>
  );
}
